# Generated by Django 5.0.3 on 2024-03-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appointments.salon'),
            preserve_default=False,
        ),
    ]
